### ISSUE TITLE
Evaluation data loading

### ISSUE THREAD

**Issue by inderjeetnair** [nlpaueb/multi-eurlex#2]
Hey,
Thanks for releasing this code. I believe that there is a small inaccuracy in your code.
In the file `experiments/trainer.py`, line number: 111, the following line of code
```
dataset=eval_dataset['validation'][:eval_samples if eval_samples else len(eval_dataset)]
```
must be replaced with
```
dataset=eval_dataset['validation'][:eval_samples if eval_samples else len(eval_dataset['validation'])]
```
I believe that `len(eval_dataset)` would be 3 as it indicates the number of splits associated with the dataset. Please let me know whether this rectification is valid.

**Comment by iliaschalkidis** [comment]
Hi @Inderbat,

Thanks for sharing. It seems I forgot to check this case when I replaced locally loaded datasets with HF datasets for ease of use.

I think the same rule (issue) applies in 3 different parts of the code (`trainer.py`), two when defining the `dev_generator` and once when defining the `test_generator`. I pushed a hotfix in the repo, let me know if there is another issue.

Thanks again!
