### ISSUE TITLE
Reproducibility of the experiments

### ISSUE THREAD

**Issue by Beam-coder** [nlpaueb/multi-eurlex#3]
Hello,

Thank you for your research and your code which are very interesting. I'm trying to reproduce your results on your paper. I called `python3 trainer.py --bert_path 'camembert-base' --native_bert True --batch_size 1  --train_lang 'fr' --eval_langs 'fr' --label_level 'level_3'`, but got `NotImplementedError: Model type camembert is not supported for adaptation`.

Thank you in advance for any reply.

**Comment by iliaschalkidis** [comment]
Hi @Beam-coder, 

Considering your first question, the `trainer` script had (until today) by default a limit of 10 samples for both training and evaluation for debugging purposes, that's why the very fast training and terrible results. I changed the defaults to `None` so the full datasets will be loaded by default since many others were confused with this.

Considering the updated question, you don't need to specify the `bert_path` to use CamemBERT. Specifying `native_bert = 'fr'` will auto-load CamemBERT as the default nativeBERT model for French, but you can still load it externally as you did. I fixed a minor bug, as there is no need for checking model types if there is no adaptation method specified.

Let me know if there is any other issue.

**Comment by Beam-coder** [comment]
Hi @iliaschalkidis ,

Thank you for your reply. It works!

I called `nohup python3 trainer.py --bert_path 'xlm-roberta-base' --batch_size 1  --train_lang 'fr' --eval_langs 'fr' --label_level 'level_3' &`, expecting to have a result of 67.2 as it is in Table 5 for One-to-one, XLM - ROBERTA; fr on your paper. However, I got 13.79...

At the end of the training, there's a message: "Allocation of 768006144 exceeds 10% of free system memory." Do you think it is due to the insufficient memories?

End of the log:

```
55000/55000 [==============================] - ETA: 0s - loss: 0.0424 - rp: 0.13392022-05-21 20:21:16.996259: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 768006144 exceeds 10% of free system memory.
2022-05-21 20:21:17.573543: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 768006144 exceeds 10% of free system memory.

55000/55000 [==============================] - 12464s 227ms/step - loss: 0.0424 - rp: 0.1339 - val_loss: 0.0487 - val_rp: 0.1132

----------------------------------------------------------------------------------------------------
Training History
----------------------------------------------------------------------------------------------------
           	Loss   		Val Loss	RP     		Val RP
EPOCH #1 : 	0.03682		0.04911		0.30970		0.10978
EPOCH #2 : 	0.04260		0.04908		0.13322		0.11651
EPOCH #3 : 	0.04252		0.04920		0.13326		0.12665
EPOCH #4 : 	0.04249		0.04976		0.13321		0.11323
EPOCH #5 : 	0.04245		0.04927		0.13373		0.11227
EPOCH #6 : 	0.04242		0.04925		0.13369		0.11582
EPOCH #7 : 	0.04238		0.04943		0.13354		0.11313
EPOCH #8 : 	0.04235		0.04874		0.13390		0.11321

----------------------------------------------------------------------------------------------------
Evaluation Metrics
----------------------------------------------------------------------------------------------------

Development
----------------------------------------------------------------------------------------------------
"fr": R-Precision: 12.67	NDCG@1: 20.10	NDCG@2: 20.56	NDCG@3: 20.57	NDCG@4: 20.19	NDCG@5: 20.71	R@1: 2.10	R@2: 4.17	R@3: 6.13	R@4: 7.81	R@5: 12.17	
----------------------------------------------------------------------------------------------------

Test
----------------------------------------------------------------------------------------------------
"fr": R-Precision: 13.79	NDCG@1: 20.72	NDCG@2: 22.21	NDCG@3: 21.77	NDCG@4: 21.11	NDCG@5: 21.25	R@1: 2.16	R@2: 4.62	R@3: 6.54	R@4: 8.18	R@5: 11.82	
----------------------------------------------------------------------------------------------------

Training time: 03:44:21 sec
Training + Evaluation time: 04:22:11 sec
```
Information about our GPUs:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 45%   61C    P2    98W / 250W |  10565MiB / 11178MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
| 36%   49C    P2    81W / 250W |  10565MiB / 11178MiB |     76%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:81:00.0 Off |                  N/A |
| 40%   54C    P2    78W / 250W |  10565MiB / 11178MiB |     79%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:82:00.0 Off |                  N/A |
| 34%   47C    P2    82W / 250W |  10565MiB / 11178MiB |     83%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1788      C   python3                                    10555MiB |
|    1      1788      C   python3                                    10555MiB |
|    2      1788      C   python3                                    10555MiB |
|    3      1788      C   python3                                    10555MiB |
+-----------------------------------------------------------------------------+
```

I tried to change batch_size to 1 in order to reduce required memory, but I found that there was no change for memory usage compared to `--batch_size 8`. Does batch_size take effect?

By the way, we can't simply set the parameter `--native_bert 'fr'` as there will be `Error: Invalid value for '--native_bert': 'fr' is not a valid boolean.`

Moreover, maybe you could consider moving trainer.py to the upper directory, as there's an error of path.

**Comment by Beam-coder** [comment]
Hi again @iliaschalkidis ,

I found the problem. Parameter "label_smoothing" should be set as 0.2.

I got 64.62 (67.4 on your paper) for XLM - ROBERTA (en), 66.75 (67.2 on your paper) for XLM - ROBERTA (fr). Still a bit different compared to your results. Do you think it is normal?

Thank you.

**Comment by iliaschalkidis** [comment]
Hi @Beam-coder,

It seems you're in the right direction. Consider also, as mentioned in the paper:

```
 For all experiments, we [...] report the average across three runs.
```

Also, make sure that you use the very same hyper-parameter values for learning rate (3e-5), batch size (8), label smoothing (0.2), and adapters' hidden size (256 hidden units; when adapters are used)  ;)

In general, small differences can occur for several minor issues, even for changing from one GPU to another or one CUDA version to another, but I think following the same hyper-parameters values reported in the paper and computing the mean across three runs will give you almost identical results 😄
