### ISSUE TITLE
Mapping for concepts from dataset to description json file

### ISSUE THREAD

**Issue by NoobVic** [nlpaueb/multi-eurlex#4]
Hi, when I get the dataset by load_dataset('multi_eurlex', language='en', label_level='level_1')

The label in these data samples are all small numbers from 0 to around 20, which I assume that they are all re-labelled by sequence.

But in the eurovoc_concepts file, the label is still 100XXX for level_1. Could you please specify the mapping relationship between them? (Same question for level 2 and level 3 as well)

Or is there any other way to interpret the labels?

Thank you very much.

**Comment by NoobVic** [comment]
By exploring the code, I found these for interpreting the concepts.

Please let me know if I am wrong about this.

line 59 to 60 in trainer.py

with open(os.path.join(DATA_DIR, 'eurovoc_concepts.json')) as file:
    label_index = {idx: concept for idx, concept in enumerate(json.load(file)[label_level])}

**Comment by iliaschalkidis** [comment]
Hi @NoobVic, yeah that's right. I also included an example here (https://huggingface.co/datasets/multi_eurlex) a while ago, because also others where interested.
