### ISSUE TITLE
Key error for "all" labels

### ISSUE THREAD

**Issue by NoobVic** [nlpaueb/multi-eurlex#5]
Hi, 

I got a key error when I try to have the original label of the data.

The code I used is load_dataset('multi_eurlex', language='en', label_level='all')

The error message is KeyError: 'all'

Could you please check about that?

Thank you very much.

**Comment by iliaschalkidis** [comment]
Hi @NoobVic,

You're right, the right call is:

```python

dataset = load_dataset('multi_eurlex', language='en', label_level='all_levels')

```

**Comment by NoobVic** [comment]
Thank you,
To get the concept description, does it refer to the 'original' in the eurovoc_concepts.jsonl?

**Comment by iliaschalkidis** [comment]
Yes
